### ISSUE TITLE
Add requirements.txt so that other people can try it out.

### ISSUE THREAD

**Issue by digi0ps** [raaguln/air-drumming#1]
Should be a simple `pip freeze > requirements.txt` if you are working in a *virtual environment*.
Or else if you are working in the global environment and have a lot of packages installed, you can try [pipreqs](https://pypi.org/project/pipreqs/) to just extract the current project's dependencies.

**Comment by raaguln** [comment]
This was a project I took upon a couple of years ago. Will refactor and enhance this rudimentary code soon in the upcoming future, and a requirements.txt and readme.md will make sense then.
